language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer dump-autoload
  - mysql -e 'create database lightFramework;'
  - mysql -uroot lightFramework < lightframework.sql

script: phpunit tests/